# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/z_eth_top.xdc

# Block Designs: bd/z_eth/z_eth.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth || ORIG_REF_NAME==z_eth}]

# IP: bd/z_eth/ip/z_eth_processing_system7_0_0/z_eth_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_processing_system7_0_0 || ORIG_REF_NAME==z_eth_processing_system7_0_0}]

# IP: bd/z_eth/ip/z_eth_SPI_Mux_0_0/z_eth_SPI_Mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_SPI_Mux_0_0 || ORIG_REF_NAME==z_eth_SPI_Mux_0_0}]

# IP: bd/z_eth/ip/z_eth_axi_ethernet_0_0/z_eth_axi_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_axi_ethernet_0_0 || ORIG_REF_NAME==z_eth_axi_ethernet_0_0}]

# IP: bd/z_eth/ip/z_eth_axi_ethernet_0_dma_1/z_eth_axi_ethernet_0_dma_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_axi_ethernet_0_dma_1 || ORIG_REF_NAME==z_eth_axi_ethernet_0_dma_1}]

# IP: bd/z_eth/ip/z_eth_axi_mem_intercon_2/z_eth_axi_mem_intercon_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_axi_mem_intercon_2 || ORIG_REF_NAME==z_eth_axi_mem_intercon_2}]

# IP: bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_0/z_eth_rst_processing_system7_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_rst_processing_system7_0_125M_0 || ORIG_REF_NAME==z_eth_rst_processing_system7_0_125M_0}]

# IP: bd/z_eth/ip/z_eth_processing_system7_0_axi_periph_1/z_eth_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==z_eth_processing_system7_0_axi_periph_1}]

# IP: bd/z_eth/ip/z_eth_xbar_2/z_eth_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_xbar_2 || ORIG_REF_NAME==z_eth_xbar_2}]

# IP: bd/z_eth/ip/z_eth_xlconcat_0_0/z_eth_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_xlconcat_0_0 || ORIG_REF_NAME==z_eth_xlconcat_0_0}]

# IP: bd/z_eth/ip/z_eth_xbar_3/z_eth_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_xbar_3 || ORIG_REF_NAME==z_eth_xbar_3}]

# IP: bd/z_eth/ip/z_eth_axi_dma_0_0/z_eth_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_axi_dma_0_0 || ORIG_REF_NAME==z_eth_axi_dma_0_0}]

# IP: bd/z_eth/ip/z_eth_axi_interconnect_0_0/z_eth_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_axi_interconnect_0_0 || ORIG_REF_NAME==z_eth_axi_interconnect_0_0}]

# IP: bd/z_eth/ip/z_eth_xbar_0/z_eth_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_xbar_0 || ORIG_REF_NAME==z_eth_xbar_0}]

# IP: bd/z_eth/ip/z_eth_Counterv5_0_0/z_eth_Counterv5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_Counterv5_0_0 || ORIG_REF_NAME==z_eth_Counterv5_0_0}]

# IP: bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_1/z_eth_rst_processing_system7_0_125M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_rst_processing_system7_0_125M_1 || ORIG_REF_NAME==z_eth_rst_processing_system7_0_125M_1}]

# IP: bd/z_eth/ip/z_eth_processing_system7_0_axi_periph_0/z_eth_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==z_eth_processing_system7_0_axi_periph_0}]

# IP: bd/z_eth/ip/z_eth_vio_0_0/z_eth_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_vio_0_0 || ORIG_REF_NAME==z_eth_vio_0_0}]

# IP: bd/z_eth/ip/z_eth_ila_0_0/z_eth_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_ila_0_0 || ORIG_REF_NAME==z_eth_ila_0_0}]

# IP: bd/z_eth/ip/z_eth_ila_1_0/z_eth_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_ila_1_0 || ORIG_REF_NAME==z_eth_ila_1_0}]

# IP: bd/z_eth/ip/z_eth_auto_pc_0/z_eth_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_auto_pc_0 || ORIG_REF_NAME==z_eth_auto_pc_0}]

# IP: bd/z_eth/ip/z_eth_auto_us_0/z_eth_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_auto_us_0 || ORIG_REF_NAME==z_eth_auto_us_0}]

# IP: bd/z_eth/ip/z_eth_auto_us_1/z_eth_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_auto_us_1 || ORIG_REF_NAME==z_eth_auto_us_1}]

# IP: bd/z_eth/ip/z_eth_auto_us_2/z_eth_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_auto_us_2 || ORIG_REF_NAME==z_eth_auto_us_2}]

# IP: bd/z_eth/ip/z_eth_auto_pc_1/z_eth_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_auto_pc_1 || ORIG_REF_NAME==z_eth_auto_pc_1}]

# IP: bd/z_eth/ip/z_eth_auto_pc_2/z_eth_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_auto_pc_2 || ORIG_REF_NAME==z_eth_auto_pc_2}]

# IP: bd/z_eth/ip/z_eth_auto_us_3/z_eth_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_auto_us_3 || ORIG_REF_NAME==z_eth_auto_us_3}]

# IP: bd/z_eth/ip/z_eth_auto_us_4/z_eth_auto_us_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_auto_us_4 || ORIG_REF_NAME==z_eth_auto_us_4}]

# IP: bd/z_eth/ip/z_eth_auto_pc_3/z_eth_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_eth_auto_pc_3 || ORIG_REF_NAME==z_eth_auto_pc_3}]

# XDC: bd/z_eth/z_eth_ooc.xdc
