# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Projects/z_eth_4_2017_02_03_1/z_eth.cache/wt [current_project]
set_property parent.project_path C:/Projects/z_eth_4_2017_02_03_1/z_eth.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/Projects/CustomIP/AXIS_Counter/AXIS_Counter_Direct_1.0
  c:/Projects/CustomIP/AXIS_Checker/AXI4_Stream_Checker_1.1
  c:/Projects/CustomIP/Cores/axis_counter_2
} [current_project]
add_files C:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/z_eth.bd
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_processing_system7_0_0/z_eth_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_ethernet_0_0/bd_0/ip/ip_0/bd_8314_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_8314_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_ethernet_0_0/bd_0/ip/ip_0/bd_8314_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_8314_eth_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_8314_eth_mac_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_8314_eth_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_8314_eth_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_ethernet_0_0/bd_0/bd_8314_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_ethernet_0_0/synth/z_eth_axi_ethernet_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_ethernet_0_dma_1/z_eth_axi_ethernet_0_dma_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_ethernet_0_dma_1/z_eth_axi_ethernet_0_dma_1.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_ethernet_0_dma_1/z_eth_axi_ethernet_0_dma_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_0/z_eth_rst_processing_system7_0_125M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_0/z_eth_rst_processing_system7_0_125M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_0/z_eth_rst_processing_system7_0_125M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_xbar_2/z_eth_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_xbar_3/z_eth_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_dma_0_0/z_eth_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_dma_0_0/z_eth_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_dma_0_0/z_eth_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_xbar_0/z_eth_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_1/z_eth_rst_processing_system7_0_125M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_1/z_eth_rst_processing_system7_0_125M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_1/z_eth_rst_processing_system7_0_125M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_vio_0_0/z_eth_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_vio_0_0/z_eth_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_ila_0_0/ila_v6_1/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_ila_0_0/z_eth_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_ila_1_0/ila_v6_1/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_ila_1_0/z_eth_ila_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_pc_0/z_eth_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_us_0/z_eth_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_us_0/z_eth_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_us_1/z_eth_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_us_1/z_eth_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_us_2/z_eth_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_us_2/z_eth_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_pc_1/z_eth_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_pc_2/z_eth_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_us_3/z_eth_auto_us_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_us_3/z_eth_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_us_4/z_eth_auto_us_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_us_4/z_eth_auto_us_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_auto_pc_3/z_eth_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/z_eth_ooc.xdc]
set_property is_locked true [get_files C:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/z_eth.bd]

read_vhdl -library xil_defaultlib {
  C:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/new/SPI_MUX.vhd
  C:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/new/AXIS_COUNTER.vhd
  C:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/hdl/z_eth_wrapper.vhd
  C:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/imports/new/z_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/constrs_1/new/z_eth_top.xdc
set_property used_in_implementation false [get_files C:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/constrs_1/new/z_eth_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top z_top -part xc7z010clg400-1


write_checkpoint -force -noxdef z_top.dcp

catch { report_utilization -file z_top_utilization_synth.rpt -pb z_top_utilization_synth.pb }
