# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_dma_0_0/z_eth_axi_dma_0_0.xci
# IP: The module: 'z_eth_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_dma_0_0/z_eth_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_eth_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_dma_0_0/z_eth_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_eth_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_dma_0_0/z_eth_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_eth_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_dma_0_0/z_eth_axi_dma_0_0.xci
# IP: The module: 'z_eth_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_dma_0_0/z_eth_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_eth_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_dma_0_0/z_eth_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_eth_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/z_eth_4_2017_02_03_1/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_axi_dma_0_0/z_eth_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_eth_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
