# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/z_eth_4/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_1/z_eth_rst_processing_system7_0_125M_1.xci
# IP: The module: 'z_eth_rst_processing_system7_0_125M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/z_eth_4/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_1/z_eth_rst_processing_system7_0_125M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_eth_rst_processing_system7_0_125M_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Projects/z_eth_4/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_1/z_eth_rst_processing_system7_0_125M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_eth_rst_processing_system7_0_125M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Projects/z_eth_4/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_1/z_eth_rst_processing_system7_0_125M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_eth_rst_processing_system7_0_125M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Projects/z_eth_4/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_1/z_eth_rst_processing_system7_0_125M_1.xci
# IP: The module: 'z_eth_rst_processing_system7_0_125M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/z_eth_4/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_1/z_eth_rst_processing_system7_0_125M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_eth_rst_processing_system7_0_125M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Projects/z_eth_4/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_1/z_eth_rst_processing_system7_0_125M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_eth_rst_processing_system7_0_125M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Projects/z_eth_4/z_eth.srcs/sources_1/bd/z_eth/ip/z_eth_rst_processing_system7_0_125M_1/z_eth_rst_processing_system7_0_125M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_eth_rst_processing_system7_0_125M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
